### PR TITLE
implementation of deduping in flight requests

### PR DESCRIPTION
**Pull request by simonxabris**
This is a solution for this issue: https://github.com/andyrichardson/tipple/issues/20

The size went from 1191 B to 1267 B which I hope is acceptable, all the tests passed and the build is successful.

I've tried out this solution in the example app and it stopped subsequent fetches when the promise from the first one was still pending.

Let me know what you think of this solution.

### CODE REVIEW

**Comment by andyrichardson** [comment]
Looks awesome. I'm pretty sure that would work :+1:

Do you think you could apply your current approach but:
 - Use a key/value store rather than an array (removes the need to filter + faster runtime perf)
 - Move the fetching logic into a utility function

If you can make those two changes, I'll be happy to merge.

For the latter, you would need to solve the problem you've recognised relating to calling "response.json()" multiple times. Maybe breaking the fetch and json parsing into a separate async function would solve this.

There's a codesandbox example below if you get stuck but give it a shot first.

<details><summary>Spoiler</summary><a href="https://codesandbox.io/s/n1lsz">
Code Sandbox
</a></details>

**Comment by simonxabris** [comment]
Will implement the two changes you said above!

Just to clarify on the second point, you want that whole function in doFetch's useCallback to be moved to a separate function in util.ts or did I get this wrong?

Also huge thanks for leading me to solution on the .json() thing, what I got wrong from the start is that I did
```javascript
const request = fetch(url, fetchArgs);
inFlight[url] = request;
```
so I stored the "raw" Promise and I couldn't really do anything with it.

**Comment by andyrichardson** [comment]
> you want that whole function in doFetch's useCallback to be moved to a separate function in util.ts or did I get this wrong?

This PR won't need to make changes to useFetch at all. I'd recommend you try going about it the way you initially planned now that you've found a way around the `response.json()` problem. useFetch doesn't need to know about dedupe logic as it's outside of its scope and useFetch is instantiated many times by different components - we want to dedup all requests, not on a per-component basis.

> I stored the "raw" Promise and I couldn't really do anything with it.

That's initially how I planned to do it until you mentioned the JSON parsing problem. Good find 👍

All you need to do is make sure you do the parsing before adding it to the inFlight collection.

There's two ways you can do that

```
// Inline with .then
const request = fetch(url, fetchArgs).then(parsing logic);
inFlight[url] = request;

// Separate async function
const request = fetchAndParse(url, fetchArgs);
inFlight[url] = request;
```

**Comment by simonxabris** [comment]
I've implemented the deduping logic in the executeRequest function based on your codeSandbox, but I modified it a little bit.

In your sandbox, requests never get removed from the inFlight object, they are just set to undefined so in a real case this object could get quite large unnecessarily (in my opinion, maybe I'm missing something here). In my implementation those requests that are already resolved are deleted from the inFlight object entirely.

I may need a little help with the typings, I've created an inFlightInterface, but I didn't want to put it in types.ts because it isn't used anywhere else so I just left it in util.ts, is it ok there?

Also typescript is pretty new to me and the `Promise<object>` part doesn't seem like the strongest of typings, but as far as I know what that Promise resolves with is whatever json the backend returns so I'm not sure how should I type it.
```javascript
[url: string]: Promise<object>;
```

**Comment by andyrichardson** [comment]
> In your sandbox, requests never get removed from the inFlight object, they are just set to undefined so in a real case this object could get quite large unnecessarily (in my opinion, maybe I'm missing something here). In my implementation those requests that are already resolved are deleted from the inFlight object entirely.

Not sure what you mean here but the reference to the promise will be dropped once a reassignment or deletion takes place. The only difference with deletion is that the object property itself is removed (negligent performance cost with negligent memory usage reduction - no real world [performance difference](https://perf.link/#Y29uc3Qga2V5cyA9IHt9Owpjb25zdCBpdGVyYXRpb25zID0gMTAwMDAwOw==/W3siY29kZSI6ImZvciAobGV0IHggPSAwOyB4IDwgaXRlcmF0aW9uczsgeCsrKSB7XG4gIGtleXNbeF0gPSAxMjM0O1xuICBkZWxldGUga2V5c1t4XTtcbn0iLCJlcnJvciI6ZmFsc2UsIm1lZGlhbiI6MTcuMzQwMDAwMDA1Nzg4MTd9LHsiY29kZSI6ImZvciAobGV0IHggPSAwOyB4IDwgaXRlcmF0aW9uczsgeCsrKSB7XG4gIGtleXNbeF0gPSAxMjM0O1xuICBrZXlzW3hdID0gdW5kZWZpbmVkO1xufSIsImVycm9yIjpmYWxzZSwibWVkaWFuIjoyLjU3NDk5OTk5MTMzODd9XQ==)) which for our cases doesn't matter as we're not using `Object.hasProperty`. In short, either works just fine so let's keep the deletion.

> I may need a little help with the typings, I've created an inFlightInterface, but I didn't want to put it in types.ts because it isn't used anywhere else so I just left it in util.ts, is it ok there?

Looks about right to me! You can use a `Record` type but again, not a huge difference.

> Also typescript is pretty new to me and the Promise part doesn't seem like the strongest of typings

While I'm not a fan of using `any`, I've been settling on that for response types (Typescript doesn't yet have a parsed JSON type and the result could be one of many types including an array). There is an `unknown` type, but in #27 this looked to make typing things way more complicated than I would have liked.

All things aside...

# Congrats on your first PR 💯 👍 🍾 🎈 🎉 

Nice work! Thanks for your contribution. Merged 👍

**Comment by simonxabris** [comment]
Thank you very much for you help and for being patient! 😃

Tipple is really good, learned a lot from going through the source, will keep an eye on it and try to contribute more if I can!

**Pull request merged**
